// Mock data for current vehicles
export const mockVehicleHistory = [
    {
      id: 1,
      validPass: "Yes",
      licenseNumber: "ABD123",
      licenseState: "SC",
      color: "Red",
      make: "Toyota",
      model: "Corolla",
      confidence: "98%",
      entry: "true", // "1" means the vehicle is inside, "0" means outside
      stamp: "2025-03-13T12:00:00Z",
    },
    {
      id: 2,
      validPass: "No",
      licenseNumber: "XYZ789",
      licenseState: "NC",
      color: "Blue",
      make: "Honda",
      model: "Civic",
      confidence: "85%",
      entry: "true",
      stamp: "2025-03-13T13:15:30Z",
    },
    {
      id: 3,
      validPass: "Yes",
      licenseNumber: "MNO456",
      licenseState: "GA",
      color: "Black",
      make: "Ford",
      model: "Mustang",
      confidence: "92%",
      entry: "true",
      stamp: "2025-03-13T14:22:10Z",
    },
    {
      id: 4,
      validPass: "Yes",
      licenseNumber: "JKL234",
      licenseState: "FL",
      color: "White",
      make: "Chevrolet",
      model: "Camaro",
      confidence: "75%",
      entry: "false",
      stamp: "2025-03-13T15:30:00Z",
    },
    {
      id: 5,
      validPass: "No",
      licenseNumber: "TUV567",
      licenseState: "TX",
      color: "Green",
      make: "Nissan",
      model: "Altima",
      confidence: "60%",
      entry: "true",
      stamp: "2025-03-13T16:40:20Z",
    },
    {
      id: 6,
      validPass: "Yes",
      licenseNumber: "DEF789",
      licenseState: "VA",
      color: "Silver",
      make: "Hyundai",
      model: "Elantra",
      confidence: "99%",
      entry: "false",
      stamp: "2025-03-13T17:05:40Z",
    },
    {
      id: 7,
      validPass: "Yes",
      licenseNumber: "GHI123",
      licenseState: "CA",
      color: "Yellow",
      make: "BMW",
      model: "X5",
      confidence: "88%",
      entry: "true",
      stamp: "2025-03-13T18:25:55Z",
    },
    {
      id: 8,
      validPass: "No",
      licenseNumber: "PQR456",
      licenseState: "NY",
      color: "Purple",
      make: "Audi",
      model: "A6",
      confidence: "65%",
      entry: "false",
      stamp: "2025-03-13T19:15:10Z",
    },
    {
      id: 9,
      validPass: "Yes",
      licenseNumber: "LMN234",
      licenseState: "PA",
      color: "Orange",
      make: "Kia",
      model: "Soul",
      confidence: "90%",
      entry: "true",
      stamp: "2025-03-13T20:10:50Z",
    },
    {
      id: 10,
      validPass: "Yes",
      licenseNumber: "RST567",
      licenseState: "MD",
      color: "Gray",
      make: "Mazda",
      model: "CX-5",
      confidence: "82%",
      entry: "false",
      stamp: "2025-03-13T21:00:30Z",
    },
  ];
  
// MockData.js
export const mockCurrentVehicles = [
    {
      id: 1,
      validPass: "Yes",
      licenseNumber: "ABD123",
      licenseState: "SC",
      color: "Red",
      make: "Toyota",
      model: "Corolla",
      confidence: "98%",
      entry: "true",
      stamp: "2025-03-13T12:00:00Z",
    },
    {
      id: 2,
      validPass: "No",
      licenseNumber: "XYZ456",
      licenseState: "GA",
      color: "Blue",
      make: "Honda",
      model: "Civic",
      confidence: "65%",
      entry: "true",
      stamp: "2025-03-13T13:00:00Z",
    },
    {
      id: 3,
      validPass: "Yes",
      licenseNumber: "JKL789",
      licenseState: "NC",
      color: "Black",
      make: "Ford",
      model: "Fusion",
      confidence: "80%",
      entry: "false",
      stamp: "2025-03-13T14:00:00Z",
    },
  ];
  
  
  // Mock data for parking lot info
  export const mockParkingInfo = [
    {
      parkingLotKey: 0,
      numSpots: 95,
      name: "Laura Lander",
      numUsed: 10, // Number of spots currently used
    },
    {
      parkingLotKey: 1,
      numSpots: 100,
      name: "North Lot",
      numUsed: 35,
    },
    {
      parkingLotKey: 2,
      numSpots: 50,
      name: "South Lot",
      numUsed: 50,
    }
  ];
  